### ISSUE TITLE
Renovate CLI incorrectly opens 'Pin Dependencies' PR

### ISSUE THREAD

**Issue by nathanpower** [renovateapp/renovate#2009] opened 2018-05-23 08:38 UTC
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate opens `pinDependencies` PR for `devDependencies`

**To Reproduce**

1.  Create repository with empty `renovate.json`
2.  Install some dev dependencies (caret version specifier)
3.  Onboard repo
4. Run renovate

**Expected behavior**
Renovate should do nothing

** Actual behaviour
Renovate opens a `Pin Dependencies` PR, pinning the version at the same version it was at (minus the caret)

Present in 12.30.12
Not present in 12.21.16

**Comment by rarkins** [comment] 2018-05-23 08:48
I was thinking this was invalid because it's intended behaviour, but I think you're right for the case where you are not using the `config:base` preset. When refactoring `pinVersions` to `rangeStrategy` (https://renovatebot.com/docs/configuration-options/#rangestrategy) I think the default behaviour changed, which is not the right thing to do semver-wise, so I will revert the default from `auto` to `replace`. Thanks for raising it.

**Comment by rarkins** [comment] 2018-05-23 16:43
Fixed in renovate@12.30.14

**Closed by rarkins** 2018-05-23 16:43 UTC
