### ISSUE TITLE
bug: recreate/rebase is broken in gitlab

### ISSUE THREAD

**Issue by evilebottnawi** [renovateapp/renovate#1468] opened 2018-02-02 11:28 UTC
```shell
 INFO: Renovating repository (repository=itgalaxy/insteria)
 INFO: renovate.json config (repository=itgalaxy/insteria)
       "config": {"pinVersions": true}
 INFO: Found package.json files (repository=itgalaxy/insteria)
       "packageJsonFiles": ["package.json"]
 INFO: Found Dockerfiles (repository=itgalaxy/insteria)
       "dockerFiles": ["tools/docker/Dockerfile"]
 INFO: Renovating package.json dependencies (repository=itgalaxy/insteria, packageFile=package.json)
 INFO: Processing package file (repository=itgalaxy/insteria, packageFile=package.json)
 INFO: 1 result(s): 7.6.1 (repository=itgalaxy/insteria, packageFile=package.json, depType=devDependencies, dependency=eslint-plugin-react)
 INFO: 1 result(s): 0.0.1-alpha.10 (repository=itgalaxy/insteria, packageFile=package.json, depType=devDependencies, dependency=webpack-webfont)
 INFO: 1 result(s): 2.10.0 (repository=itgalaxy/insteria, packageFile=package.json, depType=devDependencies, dependency=webpack-bundle-analyzer)
 INFO: Finished processing package file (repository=itgalaxy/insteria, packageFile=package.json)
 INFO: Renovating Dockerfile FROM (repository=itgalaxy/insteria, packageFile=tools/docker/Dockerfile)
 INFO: Processing Dockerfile (repository=itgalaxy/insteria, packageFile=tools/docker/Dockerfile)
 INFO: Dockerfile FROM (repository=itgalaxy/insteria, packageFile=tools/docker/Dockerfile)
       "depName": "itgalaxy/langvm",
       "currentTag": "2018.01.11",
       "currentDigest": undefined
 INFO: Error looking up docker image digest (repository=itgalaxy/insteria, packageFile=tools/docker/Dockerfile)
       "err": {
         "name": "HTTPError",
         "host": "index.docker.io",
         "hostname": "index.docker.io",
         "method": "GET",
         "path": "/v2/itgalaxy/langvm/manifests/2018.01.11",
         "protocol": "https:",
         "url": "https://index.docker.io/v2/itgalaxy/langvm/manifests/2018.01.11",
         "statusCode": 401,
         "statusMessage": "Unauthorized",
         "headers": {
           "content-type": "application/json; charset=utf-8",
           "docker-distribution-api-version": "registry/2.0",
           "www-authenticate": "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:itgalaxy/langvm:pull\",error=\"insufficient_scope\"",
           "date": "Fri, 02 Feb 2018 11:24:47 GMT",
           "content-length": "158",
           "connection": "close",
           "strict-transport-security": "max-age=31536000"
         }
       },
       "tag": "2018.01.11"
 INFO: Docker tag is not valid semver - skipping (repository=itgalaxy/insteria, packageFile=tools/docker/Dockerfile)
       "currentDepTag": "itgalaxy/langvm:2018.01.11"
 INFO: Finished processing Dockerfile (repository=itgalaxy/insteria, packageFile=tools/docker/Dockerfile)
 INFO: angular semantic commits detected (repository=itgalaxy/insteria, packageFile=tools/docker/Dockerfile)
 INFO: Processing 3 branch(es) (repository=itgalaxy/insteria)
 INFO: Branch has 1 upgrade(s) (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
ERROR: Error updating branch: 404 Branch Not Found (404) (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.itgalaxy.company",
         "hostname": "gitlab.itgalaxy.company",
         "method": "GET",
         "path": "/api/v4/projects/itgalaxy%2Finsteria/repository/branches/renovate%2Feslint-plugin-react-7.x",
         "protocol": "https:",
         "url": "https://gitlab.itgalaxy.company/api/v4/projects/itgalaxy%2Finsteria/repository/branches/renovate%2Feslint-plugin-react-7.x",
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "nginx",
           "date": "Fri, 02 Feb 2018 11:24:48 GMT",
           "content-type": "application/json",
           "content-length": "34",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-content-type-options": "nosniff",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "01c9f8ab-7358-495e-82fc-3f5c70f69e7e",
           "x-runtime": "0.011821"
         }
       }
 INFO: Branch has 1 upgrade(s) (repository=itgalaxy/insteria, dependencies=webpack-bundle-analyzer, branch=renovate/webpack-bundle-analyzer-2.x)
 INFO: Branch already exists (repository=itgalaxy/insteria, dependencies=webpack-bundle-analyzer, branch=renovate/webpack-bundle-analyzer-2.x)
 INFO: Branch is not mergeable and needs rebasing (repository=itgalaxy/insteria, dependencies=webpack-bundle-analyzer, branch=renovate/webpack-bundle-analyzer-2.x)
 INFO: Deleting unmergeable branch in order to recreate/rebase (repository=itgalaxy/insteria, dependencies=webpack-bundle-analyzer, branch=renovate/webpack-bundle-analyzer-2.x)
 INFO: Generated lockfile (repository=itgalaxy/insteria, dependencies=webpack-bundle-analyzer, branch=renovate/webpack-bundle-analyzer-2.x)
       "seconds": 8,
       "type": "package-lock.json",
       "stdout": "total 780\n-rw-r--r-- 1 root root 788459 Feb  2 14:24 package-lock.json\n-rw-r--r-- 1 root root   4731 Feb  2 14:24 package.json\n5.6.0\nadded 2454 packages in 6.974s\n",
       "stderr": ""
ERROR: Error updating branch: You can only create or edit files when you are on a branch (400) (repository=itgalaxy/insteria, dependencies=webpack-bundle-analyzer, branch=renovate/webpack-bundle-analyzer-2.x)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.itgalaxy.company",
         "hostname": "gitlab.itgalaxy.company",
         "method": "POST",
         "path": "/api/v4/projects/itgalaxy%2Finsteria/repository/files/package.json",
         "protocol": "https:",
         "url": "https://gitlab.itgalaxy.company/api/v4/projects/itgalaxy%2Finsteria/repository/files/package.json",
         "statusCode": 400,
         "statusMessage": "Bad Request",
         "headers": {
           "server": "nginx",
           "date": "Fri, 02 Feb 2018 11:24:56 GMT",
           "content-type": "application/json",
           "content-length": "72",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-content-type-options": "nosniff",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "7c890b0f-0578-4076-af5f-21e3afad179f",
           "x-runtime": "0.011011"
         }
       }
 INFO: Branch has 1 upgrade(s) (repository=itgalaxy/insteria, dependencies=webpack-webfont, branch=renovate/webpack-webfont-0.x)
 INFO: Branch already exists (repository=itgalaxy/insteria, dependencies=webpack-webfont, branch=renovate/webpack-webfont-0.x)
 INFO: Merge Request #511 does not need updating (repository=itgalaxy/insteria, dependencies=webpack-webfont, branch=renovate/webpack-webfont-0.x)
 INFO: Finished repository (repository=itgalaxy/insteria)
 INFO: Renovate finished
```

Today i updated renovate to latest and we get this error.

Don't see on docker problem, already discussion :smile:

**Comment by rarkins** [comment] 2018-02-02 11:29
@evilebottnawi can you tell me the exact versions of Renovate you upgraded from/to?

**Comment by rarkins** [comment] 2018-02-02 11:33
It seems to start with a 404 for `GET`:
```
         "path": "/api/v4/projects/itgalaxy%2Finsteria/repository/branches/renovate%2Feslint-plugin-react-7.x",
         "protocol": "https:",
         "url": "https://gitlab.itgalaxy.company/api/v4/projects/itgalaxy%2Finsteria/repository/branches/renovate%2Feslint-plugin-react-7.x",
         "statusCode": 404,
         "statusMessage": "Not Found",
```

That would be before any recreate/rebase.

**Comment by rarkins** [comment] 2018-02-02 11:36
A debug level log would be helpful to further debug. You can zip and email to me if you prefer.

**Comment by evilebottnawi** [comment] 2018-02-02 11:37
@rarkins Just FYI, would be great have command `renovate -v` (`renovate --version`) :+1:

**Comment by evilebottnawi** [comment] 2018-02-02 12:15
@rarkins Debug:
```
DEBUG: generateBranchConfig() (repository=itgalaxy/insteria, branch=renovate/eslint-plugin-react-7.x)
DEBUG: hasGroupName: false (repository=itgalaxy/insteria, branch=renovate/eslint-plugin-react-7.x)
DEBUG: groupEligible: false (repository=itgalaxy/insteria, branch=renovate/eslint-plugin-react-7.x)
DEBUG: useGroupSettings: false (repository=itgalaxy/insteria, branch=renovate/eslint-plugin-react-7.x)
DEBUG: Compiling branchName and prTitle (repository=itgalaxy/insteria, branch=renovate/eslint-plugin-react-7.x)
       "branchName": "{{{branchPrefix}}}{{{depNameSanitized}}}-{{{newVersionMajor}}}.x",
       "prTitle": "{{#if isPin}}Pin{{else}}{{#if isRollback}}Roll back{{else}}Update{{/if}}{{/if}} dependency {{{depName}}} to {{#if isRange}}{{{newVersion}}}{{else}}{{#if isMajor}}v{{{newVersionMajor}}}{{else}}v{{{newVersion}}}{{/if}}{{/if}}"
DEBUG: Upgrade has semantic commits enabled (repository=itgalaxy/insteria, branch=renovate/eslint-plugin-react-7.x)
DEBUG: renovate/eslint-plugin-react-7.x, chore(deps): update dependency eslint-plugin-react to v7.6.1 (repository=itgalaxy/insteria, branch=renovate/eslint-plugin-react-7.x)
DEBUG: generateBranchConfig() (repository=itgalaxy/insteria, branch=renovate/webpack-bundle-analyzer-2.x)
DEBUG: hasGroupName: false (repository=itgalaxy/insteria, branch=renovate/webpack-bundle-analyzer-2.x)
DEBUG: groupEligible: false (repository=itgalaxy/insteria, branch=renovate/webpack-bundle-analyzer-2.x)
DEBUG: useGroupSettings: false (repository=itgalaxy/insteria, branch=renovate/webpack-bundle-analyzer-2.x)
DEBUG: Compiling branchName and prTitle (repository=itgalaxy/insteria, branch=renovate/webpack-bundle-analyzer-2.x)
       "branchName": "{{{branchPrefix}}}{{{depNameSanitized}}}-{{{newVersionMajor}}}.x",
       "prTitle": "{{#if isPin}}Pin{{else}}{{#if isRollback}}Roll back{{else}}Update{{/if}}{{/if}} dependency {{{depName}}} to {{#if isRange}}{{{newVersion}}}{{else}}{{#if isMajor}}v{{{newVersionMajor}}}{{else}}v{{{newVersion}}}{{/if}}{{/if}}"
DEBUG: Upgrade has semantic commits enabled (repository=itgalaxy/insteria, branch=renovate/webpack-bundle-analyzer-2.x)
DEBUG: renovate/webpack-bundle-analyzer-2.x, chore(deps): update dependency webpack-bundle-analyzer to v2.10.0 (repository=itgalaxy/insteria, branch=renovate/webpack-bundle-analyzer-2.x)
DEBUG: generateBranchConfig() (repository=itgalaxy/insteria, branch=renovate/webpack-webfont-0.x)
DEBUG: hasGroupName: false (repository=itgalaxy/insteria, branch=renovate/webpack-webfont-0.x)
DEBUG: groupEligible: false (repository=itgalaxy/insteria, branch=renovate/webpack-webfont-0.x)
DEBUG: useGroupSettings: false (repository=itgalaxy/insteria, branch=renovate/webpack-webfont-0.x)
DEBUG: Compiling branchName and prTitle (repository=itgalaxy/insteria, branch=renovate/webpack-webfont-0.x)
       "branchName": "{{{branchPrefix}}}{{{depNameSanitized}}}-{{{newVersionMajor}}}.x",
       "prTitle": "{{#if isPin}}Pin{{else}}{{#if isRollback}}Roll back{{else}}Update{{/if}}{{/if}} dependency {{{depName}}} to {{#if isRange}}{{{newVersion}}}{{else}}{{#if isMajor}}v{{{newVersionMajor}}}{{else}}v{{{newVersion}}}{{/if}}{{/if}}"
DEBUG: Upgrade has semantic commits enabled (repository=itgalaxy/insteria, branch=renovate/webpack-webfont-0.x)
DEBUG: renovate/webpack-webfont-0.x, chore(deps): update dependency webpack-webfont to v0.0.1-alpha.10 (repository=itgalaxy/insteria, branch=renovate/webpack-webfont-0.x)
DEBUG: config.repoIsOnboarded=true (repository=itgalaxy/insteria)
DEBUG: Finished determining upgrades (repository=itgalaxy/insteria)
 INFO: Processing 3 branch(es) (repository=itgalaxy/insteria)
DEBUG: processBranch() (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: Checking if branch exists: renovate/eslint-plugin-react-7.x (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: GET (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
       "path": "projects/itgalaxy%2Finsteria/repository/branches/renovate%2Feslint-plugin-react-7.x"
DEBUG: Branch doesn't exist (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: branchExists=false (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
 INFO: Branch has 1 upgrade(s) (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: recreateClosed is false (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: findPr(renovate/eslint-plugin-react-7.x, chore(deps): update dependency eslint-plugin-react to v7.6.1, closed) (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: findPr(renovate/eslint-plugin-react-7.x, chore(deps): update dependency eslint-plugin-react to version 7.6.1, closed) (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: prAlreadyExisted=false (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: Checking if PR has been edited (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: findPr(renovate/eslint-plugin-react-7.x, chore(deps): update dependency eslint-plugin-react to v7.6.1, open) (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: Found existing PR (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
       "pr": {
         "number": 1264,
         "branchName": "renovate/eslint-plugin-react-7.x",
         "title": "chore(deps): update dependency eslint-plugin-react to v7.6.1",
         "state": "open",
         "createdAt": "2018-01-25T22:55:36.406Z"
       }
DEBUG: getPr(1264) (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: GET (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
       "path": "projects/itgalaxy%2Finsteria/merge_requests/1264"
DEBUG: pr cannot be merged (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
DEBUG: GET (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
       "path": "projects/itgalaxy%2Finsteria/repository/branches/renovate%2Feslint-plugin-react-7.x"
ERROR: Error updating branch: 404 Branch Not Found (404) (repository=itgalaxy/insteria, dependencies=eslint-plugin-react, branch=renovate/eslint-plugin-react-7.x)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.itgalaxy.company",
         "hostname": "gitlab.itgalaxy.company",
         "method": "GET",
         "path": "/api/v4/projects/itgalaxy%2Finsteria/repository/branches/renovate%2Feslint-plugin-react-7.x",
         "protocol": "https:",
         "url": "https://gitlab.itgalaxy.company/api/v4/projects/itgalaxy%2Finsteria/repository/branches/renovate%2Feslint-plugin-react-7.x",
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "nginx",
           "date": "Fri, 02 Feb 2018 12:13:27 GMT",
           "content-type": "application/json",
           "content-length": "34",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-content-type-options": "nosniff",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "76379729-268b-45f5-b154-84593056523b",
           "x-runtime": "0.039261"
         }
       }
```

**Comment by evilebottnawi** [comment] 2018-02-02 12:16
This happens when we merge update. First message was about conflict, when renovate removed branch and when we got this error.

**Comment by rarkins** [comment] 2018-02-02 12:29
Is the MR (#1264) open but the branch (`renovate/eslint-plugin-react-7.x`) is removed?

**Comment by evilebottnawi** [comment] 2018-02-02 12:42
@rarkins MR exists. branch no

**Comment by rarkins** [comment] 2018-02-02 12:54
OK, then it makes some sense as to why it's producing this error, although I don't know why it ended up getting deleted but not then updated. Any chance you have the log from when Renovate deleted that branch? Assuming it wasn't a human that did it.

FYI the way we rebase is different between GitHub the GitLab:

GitHub: if you delete a branch, GitHub closes the PR that was attached. So instead we use GitHub's low-level git operations API to essentially "force push" an update to the existing branch.

GitLab: No git operations available, but when you delete a branch then the PR is not closed, so we can delete the branch and recreate it in order to update the PR without closing it.

**Comment by evilebottnawi** [comment] 2018-02-02 12:59
@rarkins renovate delete branch. Maybe something wrong in api gitlab? I can try to update to latest version.

**Comment by rarkins** [comment] 2018-02-02 13:26
Well it's always good to update to the latest, but I think this will require a fix. In the meantime if you're in a hurry you can delete that orphaned PR though.

**Comment by evilebottnawi** [comment] 2018-02-02 13:39
@rarkins better wait fix, we have a lot of this PR in many repos

**Comment by evilebottnawi** [comment] 2018-02-02 13:48
@rarkins Steps:
1. Renovate create MR (example `package-1`)
2. Renovate create other MR (example `package-2`)
3. We merge `package-1`. We can't merge `package-2` because they have conflict in lock file.
4. Renovate delete branch `package-2`, but MR exists (seems he try rebase).
5. That all. I try to run manually renovate and get error above.

**Comment by rarkins** [comment] 2018-02-03 12:09
@evilebottnawi I was able to reproduce it and fix it in my test repository. Could you try out `renovate@11.16.9`?

**Comment by evilebottnawi** [comment] 2018-02-05 10:10
@rarkins Thanks all works fine!

**Comment by evilebottnawi** [comment] 2018-02-27 10:06
@rarkins seems problem returned again :disappointed:

**Comment by rarkins** [comment] 2018-02-27 10:07
Same steps to reproduce?

**Comment by evilebottnawi** [comment] 2018-02-27 10:16
@rarkins As above 1, 2, 3, 4
5. Renovate do request and get:
```shell
"statusCode": 403,
       "message": "API rate limit exceeded for 109.194.204.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (403)"
```

I known what is mean, but after rate is normalize renovate don't create new branch

**Comment by rarkins** [comment] 2018-02-27 10:19
And it happens every time?

That’s very strange, because every request we send should be authenticated. Or is that rate limit coking from GitHub when it’s looking up release notes?

**Comment by evilebottnawi** [comment] 2018-02-27 10:20
@rarkins not every time, but often, maybe, i don't known, what information i can provide?

**Comment by rarkins** [comment] 2018-02-27 10:22
Yes seems to be a GitHub rate limit issue. If you set a GITHUB_TOKEN env variable then you should avoid this error from GitHub but I’m interested if it doesn’t create the branch correctly next run

**Comment by rarkins** [comment] 2018-02-27 10:25
Closing this issue again as this new behaviour is not the same as the old issue. Please open a new issue or two if necessary once you’ve tested with setting a GitHub token. Every time a dependency is updated we check for release notes if the source repo is on GitHub so if you run often or have a lot of deps when you do then you may hit GitHub’s unauthenticated APi limit.

**Closed by rarkins** 2018-02-27 10:25 UTC
Labels: fix, needs-requirements, pri2-important

**Comment by evilebottnawi** [comment] 2018-02-27 10:41
@rarkins after set GITHUB_TOKEN i get again problem when renovate don't recreate branch

**Comment by rarkins** [comment] 2018-02-27 10:53
That’s a pity, please raise a new issue with steps to reproduce and I’ll look at it

**Comment by rarkins** [comment] 2018-02-27 10:53
Btw debut log should hopefully give some indication of why, if reproducing is hard

**Comment by evilebottnawi** [comment] 2018-02-27 11:14
@rarkins all steps above, step by step, and debug log same, try to debug source code :+1:

**Comment by rarkins** [comment] 2018-02-27 11:57
I guarantee you it’s not the same as before. We even changed the API used to create commits on GitLab since this issue was first closed. Please raise a new issue and copy paste what is relevant and add anything new.

**Comment by evilebottnawi** [comment] 2018-02-27 12:00
@rarkins right now i debug code to found problem, also first i try to update `gitlab` to latest version and renovate remove just some branches :confused:

**Comment by rarkins** [comment] 2018-02-27 12:10
Please keep debug logs for each run in case we need to fix anything! Renovate will autoclose any branches of its own that shouldn’t be there.

**Comment by evilebottnawi** [comment] 2018-02-27 17:48
It is hard to detect problem :disappointed: 
Debug log:
```shell
DEBUG: processBranch() (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: Checking if branch exists: renovate/spdx-expression-parse-3.x (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: GET (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
       "path": "projects/itgalaxy%2Finsteria/repository/branches/renovate%2Fspdx-expression-parse-3.x"
DEBUG: Branch doesn't exist (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: branchExists=false (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
 INFO: Branch has 1 upgrade(s) (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: recreateClosed is false (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: findPr(renovate/spdx-expression-parse-3.x, chore(deps): update dependency spdx-expression-parse to v3, closed) (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: findPr(renovate/spdx-expression-parse-3.x, chore(deps): update dependency spdx-expression-parse to version 3.x, closed) (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: prAlreadyExisted=false (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: Checking if PR has been edited (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: findPr(renovate/spdx-expression-parse-3.x, chore(deps): update dependency spdx-expression-parse to v3, open) (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: Found existing PR (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
       "pr": {
         "number": 1405,
         "branchName": "renovate/spdx-expression-parse-3.x",
         "title": "chore(deps): update dependency spdx-expression-parse to v3",
         "state": "open",
         "createdAt": "2018-02-27T00:41:55.339Z"
       }
DEBUG: getPr(1405) (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: GET (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
       "path": "projects/itgalaxy%2Finsteria/merge_requests/1405"
DEBUG: pr cannot be merged (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
DEBUG: GET (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
       "path": "projects/itgalaxy%2Finsteria/repository/branches/renovate%2Fspdx-expression-parse-3.x"
ERROR: Error updating branch: 404 Branch Not Found (404) (repository=itgalaxy/insteria, dependencies=spdx-expression-parse, branch=renovate/spdx-expression-parse-3.x)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.itgalaxy.company",
         "hostname": "gitlab.itgalaxy.company",
         "method": "GET",
         "path": "/api/v4/projects/itgalaxy%2Finsteria/repository/branches/renovate%2Fspdx-expression-parse-3.x",
         "protocol": "https:",
         "url": "https://gitlab.itgalaxy.company/api/v4/projects/itgalaxy%2Finsteria/repository/branches/renovate%2Fspdx-expression-parse-3.x",
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "nginx",
           "date": "Tue, 27 Feb 2018 17:46:04 GMT",
           "content-type": "application/json",
           "content-length": "34",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-content-type-options": "nosniff",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "c2dbd34c-3af7-45ff-a481-559d210ab099",
           "x-runtime": "0.012658"
         }
       }
```

**Comment by rarkins** [comment] 2018-02-27 17:53
Thanks, I'll do a code review and see if I can guess

**Comment by rarkins** [comment] 2018-02-27 17:54
By the way, if you rename then close that MR #1405 then it may recover/work again. It looks to be erroring because the MR exists while the branch doesn't.

**Comment by evilebottnawi** [comment] 2018-02-27 17:56
@rarkins confirm, after rename MR all works as expected :star: Bug in renovate? Maybe i can help with this?

**Comment by rarkins** [comment] 2018-02-27 18:27
Instead of checking that the PR exists, we need to check that both the PR *and* branch exists. It's hopefully just a 1-2 line fix so I can get to it soon.

**Comment by evilebottnawi** [comment] 2018-02-27 18:42
@rarkins thanks! Ping me when you will fix it :+1:

**Comment by rarkins** [comment] 2018-02-28 03:50
I added a number of checks to v11.25.22 that should avoid this problem in future, if a PR ever gets stuck without a branch

**Comment by evilebottnawi** [comment] 2018-02-28 09:57
@rarkins Thanks! All works as expected :star:
