### ISSUE TITLE
Consider adding a configuration option to "lock-step" version upgrades

### ISSUE THREAD

**Issue by kamal** [renovateapp/renovate#1276] opened 2017-12-07 18:05 UTC
Versioning schemes for `@types` packages typically follow the package they are typing. For example, `graphql` 0.10.x has `@types/graphql` 0.10.x and `graphql` 0.11.x has `@types/graphql` 0.11.x. This would make sense as a package group setting.

**Comment by rarkins** [comment] 2017-12-07 18:40
Hi @kamal, thanks for raising this issue. I will close it as a duplicate of #519 as I think that you and @ikatyang are interested in the same thing. I will copy/paste your description there.

**Closed by rarkins** 2017-12-07 18:40 UTC
